/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const RiskPrediction = IDL.Record({
  'riskCategory' : IDL.Text,
  'riskPercentage' : IDL.Float64,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'predictOutbreakRisk' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [RiskPrediction],
      [],
    ),
  'resetHistoricalData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const RiskPrediction = IDL.Record({
    'riskCategory' : IDL.Text,
    'riskPercentage' : IDL.Float64,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'predictOutbreakRisk' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [RiskPrediction],
        [],
      ),
    'resetHistoricalData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };