/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RiskPrediction {
  'riskCategory' : string,
  'riskPercentage' : number,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface WardData {
  'turbidity' : number,
  'bacteriaIndex' : number,
  'humidity' : number,
  'rainfall' : number,
  'riskPrediction' : RiskPrediction,
}
export type WardKey = bigint;
export interface WardReference {
  'fullName' : string,
  'riskColor' : string,
  'mapCellDescription' : string,
  'wardNumber' : WardKey,
}
export interface _SERVICE {
  'calculateAndPersistRisk' : ActorMethod<
    [WardKey, number, number, number, number],
    [] | [RiskPrediction]
  >,
  'getAllPersistedWardData' : ActorMethod<[], Array<[WardKey, WardData]>>,
  'getAllWardColors' : ActorMethod<[], Array<[WardKey, string]>>,
  'getExistingRiskPrediction' : ActorMethod<[WardKey], [] | [RiskPrediction]>,
  'getWardReferences' : ActorMethod<[], Array<WardReference>>,
  'resetHistoricalData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];